name: Terraform Apply (Dev)

on:
  push:
    branches: [dev]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::557690622944:role/github-actions-role
          aws-region: ${{ secrets.DEV_AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: terraform/envs/dev
        run: terraform init

      - name: Terraform Format
        working-directory: terraform
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: terraform/envs/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform/envs/dev
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        id: apply
        working-directory: terraform/envs/dev
        run: terraform apply tfplan

      - name: Save ECR URL
        working-directory: terraform/envs/dev
        run: terraform output -raw ecr_repository_url > ecr_repo_url.txt

      - name: Verify ECR URL file
        working-directory: terraform/envs/dev
        run: |
          cat ecr_repo_url.txt

      - name: Upload ECR URL artifact
        uses: actions/upload-artifact@v4
        with:
          name: ecr-url-dev
          path: terraform/envs/dev/ecr_repo_url.txt
